### ISSUE TITLE
[FEATURE] Bot that identifies Build Errors in the CI Logs

### ISSUE THREAD

**Issue by lupyuen** [apache/nuttx#13827]
### Is your feature request related to a problem? Please describe.

Right now we spend a lot of time scanning the CI Build Logs to figure out why the build failed: [Sample Log for arm-05](https://github.com/apache/nuttx/actions/runs/11189190981/job/31109249405)

```text
CMake Error at /github/workspace/sources/nuttx/build/_deps/mynewt-nimble-subbuild/mynewt-nimble-populate-prefix/src/mynewt-nimble-populate-stamp/download-mynewt-nimble-populate.cmake:170 (message):
  Each download failed!
    error: downloading 'https://github.com/apache/mynewt-nimble/archive/fb15c844542e812ceb49ab5ac8502dc93c167b90.tar.gz' failed
```

What if our [PR Bot](https://lupyuen.codeberg.page/articles/llm.html) could scan the CI Build Logs, identify the error and post as a __PR Comment__?

> _Hello! Your CI Build Failed because of this error:_
> _CMake Error at ... error: downloading ..._

#### How To Identify Errors

Our Bot will do this with `diff`, the Conventional Non-AI Way:
- The above error is from the `arm-05` Build Log. Our Bot will search the CI Build Logs, to find the __Last Successful Merge Build__ of `arm-05`: [Last Successful arm-05 Log](https://github.com/apache/nuttx/actions/runs/11171882971/job/31057495155)
- Our Bot runs a (special kind of) `diff`, to __Compare the Failed Build__ with the Last Successful Build
- It will discover the `CMake Error`, then post it as a __PR Comment__
- How is our Bot triggered? It scans the CI Builds every minute, looking for Failed Builds

#### Optional: Explain the Error with LLM

This is totally optional: Our Bot could pass the error to an LLM and explain it...

##### LLM Prompt

_What's failing in this NuttX Job for Continuous Integration? Please explain concisely_

```text
CMake Error at /github/workspace/sources/nuttx/build/_deps/mynewt-nimble-subbuild/mynewt-nimble-populate-prefix/src/mynewt-nimble-populate-stamp/download-mynewt-nimble-populate.cmake:170 (message):
  Each download failed!
    error: downloading 'https://github.com/apache/mynewt-nimble/archive/fb15c844542e812ceb49ab5ac8502dc93c167b90.tar.gz' failed
          status_code: 28
          status_string: "Timeout was reached"
          log:
          --- LOG BEGIN ---
            Trying 140.82.114.3:443...
  Connection timed out after 30001 milliseconds
  Closing connection 0
          --- LOG END ---
FAILED: mynewt-nimble-populate-prefix/src/mynewt-nimble-populate-stamp/mynewt-nimble-populate-download /github/workspace/sources/nuttx/build/_deps/mynewt-nimble-subbuild/mynewt-nimble-populate-prefix/src/mynewt-nimble-populate-stamp/mynewt-nimble-populate-download 
````

##### Response from Gemini Pro 1.5

_The CI job is failing because it's timing out while trying to download the mynewt-nimble source code from GitHub. This is likely due to a temporary network issue or GitHub server being overloaded._

_**Concisely:** The CI job can't download the required mynewt-nimble source code due to a connection timeout._

### Verification

- [X] I have verified before submitting the report.

**Comment by acassis** [comment]
@lupyuen I think sometimes the download fails for random network instability. Maybe just adding an way to retry could fix the issue.

**Comment by lupyuen** [comment]
@acassis Yep great idea! I think we need a privileged account to retry the build, I won't think we should run bots with privileged accounts though 🤔

**Comment by lupyuen** [comment]
Wonder if this will work: Instead of a Bot, we add a Job to our CI, that will watch for Timeout Errors and retry the Failed Job: https://stackoverflow.com/a/78314483
```yaml
name: Retry workflow
on:
    workflow_dispatch:
        inputs:
            run_id:
                required: true
jobs:
    rerun:
        runs-on: ubuntu-latest
        steps:
            - name: rerun ${{ inputs.run_id }}
              env:
                  GH_REPO: ${{ github.repository }}
                  GH_TOKEN: ${{ github.token }}
              run: |
                  ## TODO: Check for timeout errors
                  gh run watch ${{ inputs.run_id }} > /dev/null 2>&1
                  gh run rerun ${{ inputs.run_id }} --failed
```
